/* PandaRadio.c generated by valac 0.10.0, the Vala compiler
 * generated from PandaRadio.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <libsoup/soup.h>
#include <stdio.h>
#include <gmodule.h>


#define TYPE_PANDA_PLUGIN (panda_plugin_get_type ())
#define PANDA_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANDA_PLUGIN, PandaPlugin))
#define IS_PANDA_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANDA_PLUGIN))
#define PANDA_PLUGIN_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_PANDA_PLUGIN, PandaPluginIface))

typedef struct _PandaPlugin PandaPlugin;
typedef struct _PandaPluginIface PandaPluginIface;

#define TYPE_PANDA_RADIO (panda_radio_get_type ())
#define PANDA_RADIO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANDA_RADIO, PandaRadio))
#define PANDA_RADIO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANDA_RADIO, PandaRadioClass))
#define IS_PANDA_RADIO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANDA_RADIO))
#define IS_PANDA_RADIO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANDA_RADIO))
#define PANDA_RADIO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANDA_RADIO, PandaRadioClass))

typedef struct _PandaRadio PandaRadio;
typedef struct _PandaRadioClass PandaRadioClass;
typedef struct _PandaRadioPrivate PandaRadioPrivate;

#define TYPE_PANDA_PLAYER (panda_player_get_type ())
#define PANDA_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANDA_PLAYER, PandaPlayer))
#define PANDA_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANDA_PLAYER, PandaPlayerClass))
#define IS_PANDA_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANDA_PLAYER))
#define IS_PANDA_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANDA_PLAYER))
#define PANDA_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANDA_PLAYER, PandaPlayerClass))

typedef struct _PandaPlayer PandaPlayer;
typedef struct _PandaPlayerClass PandaPlayerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _soup_buffer_free0(var) ((var == NULL) ? NULL : (var = (soup_buffer_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _PandaPluginIface {
	GTypeInterface parent_iface;
	char* (*get_handler_path) (PandaPlugin* self);
	void (*request_handler) (PandaPlugin* self, SoupServer* server, SoupMessage* msg, const char* path, GHashTable* query, SoupClientContext* client);
};

struct _PandaRadio {
	GObject parent_instance;
	PandaRadioPrivate * priv;
};

struct _PandaRadioClass {
	GObjectClass parent_class;
};

struct _PandaRadioPrivate {
	PandaPlayer* player;
};


static gpointer panda_radio_parent_class = NULL;
static PandaPluginIface* panda_radio_panda_plugin_parent_iface = NULL;

GType panda_plugin_get_type (void) G_GNUC_CONST;
GType panda_radio_get_type (void) G_GNUC_CONST;
GType panda_player_get_type (void) G_GNUC_CONST;
#define PANDA_RADIO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_PANDA_RADIO, PandaRadioPrivate))
enum  {
	PANDA_RADIO_DUMMY_PROPERTY
};
static char* panda_radio_real_get_handler_path (PandaPlugin* base);
static void panda_radio_real_request_handler (PandaPlugin* base, SoupServer* server, SoupMessage* msg, const char* path, GHashTable* query, SoupClientContext* client);
PandaPlayer* panda_player_new (void);
PandaPlayer* panda_player_construct (GType object_type);
void panda_player_open (PandaPlayer* self, const char* stream);
void panda_player_play (PandaPlayer* self);
void panda_player_pause (PandaPlayer* self);
PandaRadio* panda_radio_new (void);
PandaRadio* panda_radio_construct (GType object_type);
static void panda_radio_finalize (GObject* obj);
GType register_plugin (GModule* module);
static int _vala_strcmp0 (const char * str1, const char * str2);



static char* panda_radio_real_get_handler_path (PandaPlugin* base) {
	PandaRadio * self;
	char* result = NULL;
	self = (PandaRadio*) base;
	result = g_strdup ("/radio.json");
	return result;
}


static void panda_radio_real_request_handler (PandaPlugin* base, SoupServer* server, SoupMessage* msg, const char* path, GHashTable* query, SoupClientContext* client) {
	PandaRadio * self;
	SoupBuffer* _tmp1_;
	char* _tmp2_;
	char* response;
	char* company;
	char* _tmp3_;
	self = (PandaRadio*) base;
	g_return_if_fail (server != NULL);
	g_return_if_fail (msg != NULL);
	g_return_if_fail (path != NULL);
	if (self->priv->player == NULL) {
		PandaPlayer* _tmp0_;
		self->priv->player = (_tmp0_ = panda_player_new (), _g_object_unref0 (self->priv->player), _tmp0_);
	}
	response = (_tmp2_ = g_strdup ((_tmp1_ = soup_message_body_flatten (msg->request_body))->data), _soup_buffer_free0 (_tmp1_), _tmp2_);
	company = g_strdup ((const char*) g_hash_table_lookup (query, "command"));
	if (_vala_strcmp0 (company, "play") == 0) {
		char* url;
		url = g_strdup ((const char*) g_hash_table_lookup (query, "url"));
		fprintf (stdout, "%s\n", url);
		if (url != NULL) {
			panda_player_open (self->priv->player, url);
			panda_player_play (self->priv->player);
		}
		_g_free0 (url);
	} else {
		panda_player_pause (self->priv->player);
	}
	soup_message_set_response (msg, "text/html", SOUP_MEMORY_COPY, _tmp3_ = g_strconcat (response, company, NULL), strlen (response) + strlen (company));
	_g_free0 (_tmp3_);
	soup_message_set_status (msg, (guint) SOUP_STATUS_OK);
	_g_free0 (company);
	_g_free0 (response);
}


PandaRadio* panda_radio_construct (GType object_type) {
	PandaRadio * self;
	self = (PandaRadio*) g_object_new (object_type, NULL);
	return self;
}


PandaRadio* panda_radio_new (void) {
	return panda_radio_construct (TYPE_PANDA_RADIO);
}


static void panda_radio_class_init (PandaRadioClass * klass) {
	panda_radio_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (PandaRadioPrivate));
	G_OBJECT_CLASS (klass)->finalize = panda_radio_finalize;
}


static void panda_radio_panda_plugin_interface_init (PandaPluginIface * iface) {
	panda_radio_panda_plugin_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_handler_path = panda_radio_real_get_handler_path;
	iface->request_handler = panda_radio_real_request_handler;
}


static void panda_radio_instance_init (PandaRadio * self) {
	self->priv = PANDA_RADIO_GET_PRIVATE (self);
}


static void panda_radio_finalize (GObject* obj) {
	PandaRadio * self;
	self = PANDA_RADIO (obj);
	_g_object_unref0 (self->priv->player);
	G_OBJECT_CLASS (panda_radio_parent_class)->finalize (obj);
}


GType panda_radio_get_type (void) {
	static volatile gsize panda_radio_type_id__volatile = 0;
	if (g_once_init_enter (&panda_radio_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PandaRadioClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panda_radio_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PandaRadio), 0, (GInstanceInitFunc) panda_radio_instance_init, NULL };
		static const GInterfaceInfo panda_plugin_info = { (GInterfaceInitFunc) panda_radio_panda_plugin_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType panda_radio_type_id;
		panda_radio_type_id = g_type_register_static (G_TYPE_OBJECT, "PandaRadio", &g_define_type_info, 0);
		g_type_add_interface_static (panda_radio_type_id, TYPE_PANDA_PLUGIN, &panda_plugin_info);
		g_once_init_leave (&panda_radio_type_id__volatile, panda_radio_type_id);
	}
	return panda_radio_type_id__volatile;
}


GType register_plugin (GModule* module) {
	GType result = 0UL;
	g_return_val_if_fail (module != NULL, 0UL);
	result = TYPE_PANDA_RADIO;
	return result;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




