/* main.c generated by valac 0.10.0, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gst/gst.h>


#define TYPE_PANDA (panda_get_type ())
#define PANDA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANDA, Panda))
#define PANDA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANDA, PandaClass))
#define IS_PANDA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANDA))
#define IS_PANDA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANDA))
#define PANDA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANDA, PandaClass))

typedef struct _Panda Panda;
typedef struct _PandaClass PandaClass;
typedef struct _PandaPrivate PandaPrivate;

#define TYPE_PANDA_SERVER (panda_server_get_type ())
#define PANDA_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANDA_SERVER, PandaServer))
#define PANDA_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANDA_SERVER, PandaServerClass))
#define IS_PANDA_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANDA_SERVER))
#define IS_PANDA_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANDA_SERVER))
#define PANDA_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANDA_SERVER, PandaServerClass))

typedef struct _PandaServer PandaServer;
typedef struct _PandaServerClass PandaServerClass;
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _Panda {
	GObject parent_instance;
	PandaPrivate * priv;
};

struct _PandaClass {
	GObjectClass parent_class;
};


static gpointer panda_parent_class = NULL;

GType panda_get_type (void) G_GNUC_CONST;
enum  {
	PANDA_DUMMY_PROPERTY
};
gint panda_main (char** args, int args_length1);
PandaServer* panda_server_new (gint port);
PandaServer* panda_server_construct (GType object_type, gint port);
GType panda_server_get_type (void) G_GNUC_CONST;
void panda_server_run (PandaServer* self);
Panda* panda_new (void);
Panda* panda_construct (GType object_type);



#line 6 "main.vala"
gint panda_main (char** args, int args_length1) {
#line 64 "main.c"
	gint result = 0;
	PandaServer* server;
	GMainLoop* _tmp0_;
#line 7 "main.vala"
	gst_init (&args_length1, &args);
#line 8 "main.vala"
	server = panda_server_new (8088);
#line 9 "main.vala"
	panda_server_run (server);
#line 10 "main.vala"
	g_main_loop_run (_tmp0_ = g_main_loop_new (NULL, FALSE));
#line 76 "main.c"
	_g_main_loop_unref0 (_tmp0_);
	result = 0;
	_g_object_unref0 (server);
#line 11 "main.vala"
	return result;
#line 82 "main.c"
}


#line 6 "main.vala"
int main (int argc, char ** argv) {
#line 88 "main.c"
	g_thread_init (NULL);
#line 6 "main.vala"
	g_type_init ();
#line 6 "main.vala"
	return panda_main (argv, argc);
#line 94 "main.c"
}


#line 3 "main.vala"
Panda* panda_construct (GType object_type) {
#line 100 "main.c"
	Panda * self;
#line 3 "main.vala"
	self = (Panda*) g_object_new (object_type, NULL);
#line 104 "main.c"
	return self;
}


#line 3 "main.vala"
Panda* panda_new (void) {
#line 3 "main.vala"
	return panda_construct (TYPE_PANDA);
#line 113 "main.c"
}


static void panda_class_init (PandaClass * klass) {
	panda_parent_class = g_type_class_peek_parent (klass);
}


static void panda_instance_init (Panda * self) {
}


GType panda_get_type (void) {
	static volatile gsize panda_type_id__volatile = 0;
	if (g_once_init_enter (&panda_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PandaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panda_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Panda), 0, (GInstanceInitFunc) panda_instance_init, NULL };
		GType panda_type_id;
		panda_type_id = g_type_register_static (G_TYPE_OBJECT, "Panda", &g_define_type_info, 0);
		g_once_init_leave (&panda_type_id__volatile, panda_type_id);
	}
	return panda_type_id__volatile;
}




