/* PandaConfig.c generated by valac 0.10.0, the Vala compiler
 * generated from PandaConfig.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_PANDA_CONFIG (panda_config_get_type ())
#define PANDA_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANDA_CONFIG, PandaConfig))
#define PANDA_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANDA_CONFIG, PandaConfigClass))
#define IS_PANDA_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANDA_CONFIG))
#define IS_PANDA_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANDA_CONFIG))
#define PANDA_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANDA_CONFIG, PandaConfigClass))

typedef struct _PandaConfig PandaConfig;
typedef struct _PandaConfigClass PandaConfigClass;
typedef struct _PandaConfigPrivate PandaConfigPrivate;

struct _PandaConfig {
	GObject parent_instance;
	PandaConfigPrivate * priv;
};

struct _PandaConfigClass {
	GObjectClass parent_class;
};


extern char* panda_config_PLUGIN_CONFIG;
char* panda_config_PLUGIN_CONFIG = NULL;
static gpointer panda_config_parent_class = NULL;

GType panda_config_get_type (void) G_GNUC_CONST;
enum  {
	PANDA_CONFIG_DUMMY_PROPERTY
};
PandaConfig* panda_config_new (void);
PandaConfig* panda_config_construct (GType object_type);
static void panda_config_finalize (GObject* obj);



#line 3 "PandaConfig.vala"
PandaConfig* panda_config_construct (GType object_type) {
#line 49 "PandaConfig.c"
	PandaConfig * self;
#line 3 "PandaConfig.vala"
	self = (PandaConfig*) g_object_new (object_type, NULL);
#line 53 "PandaConfig.c"
	return self;
}


#line 3 "PandaConfig.vala"
PandaConfig* panda_config_new (void) {
#line 3 "PandaConfig.vala"
	return panda_config_construct (TYPE_PANDA_CONFIG);
#line 62 "PandaConfig.c"
}


static void panda_config_class_init (PandaConfigClass * klass) {
	panda_config_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = panda_config_finalize;
	panda_config_PLUGIN_CONFIG = g_strdup ("plugin.json");
}


static void panda_config_instance_init (PandaConfig * self) {
}


static void panda_config_finalize (GObject* obj) {
	PandaConfig * self;
	self = PANDA_CONFIG (obj);
	G_OBJECT_CLASS (panda_config_parent_class)->finalize (obj);
}


GType panda_config_get_type (void) {
	static volatile gsize panda_config_type_id__volatile = 0;
	if (g_once_init_enter (&panda_config_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PandaConfigClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panda_config_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PandaConfig), 0, (GInstanceInitFunc) panda_config_instance_init, NULL };
		GType panda_config_type_id;
		panda_config_type_id = g_type_register_static (G_TYPE_OBJECT, "PandaConfig", &g_define_type_info, 0);
		g_once_init_leave (&panda_config_type_id__volatile, panda_config_type_id);
	}
	return panda_config_type_id__volatile;
}




