/* PandaClient.c generated by valac 0.10.0, the Vala compiler
 * generated from PandaClient.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <libsoup/soup.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_PANDA_CLIENT (panda_client_get_type ())
#define PANDA_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANDA_CLIENT, PandaClient))
#define PANDA_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PANDA_CLIENT, PandaClientClass))
#define IS_PANDA_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANDA_CLIENT))
#define IS_PANDA_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PANDA_CLIENT))
#define PANDA_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PANDA_CLIENT, PandaClientClass))

typedef struct _PandaClient PandaClient;
typedef struct _PandaClientClass PandaClientClass;
typedef struct _PandaClientPrivate PandaClientPrivate;

struct _PandaClient {
	GObject parent_instance;
	PandaClientPrivate * priv;
};

struct _PandaClientClass {
	GObjectClass parent_class;
};


static gpointer panda_client_parent_class = NULL;

GType panda_client_get_type (void) G_GNUC_CONST;
enum  {
	PANDA_CLIENT_DUMMY_PROPERTY
};
PandaClient* panda_client_new (void);
PandaClient* panda_client_construct (GType object_type);
void panda_client_request_handler (PandaClient* self, SoupServer* server, SoupMessage* msg, const char* path, GHashTable* query, SoupClientContext* client);



#line 6 "PandaClient.vala"
PandaClient* panda_client_construct (GType object_type) {
#line 48 "PandaClient.c"
	PandaClient * self;
#line 6 "PandaClient.vala"
	self = (PandaClient*) g_object_new (object_type, NULL);
#line 52 "PandaClient.c"
	return self;
}


#line 6 "PandaClient.vala"
PandaClient* panda_client_new (void) {
#line 6 "PandaClient.vala"
	return panda_client_construct (TYPE_PANDA_CLIENT);
#line 61 "PandaClient.c"
}


#line 9 "PandaClient.vala"
void panda_client_request_handler (PandaClient* self, SoupServer* server, SoupMessage* msg, const char* path, GHashTable* query, SoupClientContext* client) {
#line 9 "PandaClient.vala"
	g_return_if_fail (self != NULL);
#line 9 "PandaClient.vala"
	g_return_if_fail (server != NULL);
#line 9 "PandaClient.vala"
	g_return_if_fail (msg != NULL);
#line 9 "PandaClient.vala"
	g_return_if_fail (path != NULL);
#line 9 "PandaClient.vala"
	g_return_if_fail (client != NULL);
#line 77 "PandaClient.c"
}


static void panda_client_class_init (PandaClientClass * klass) {
	panda_client_parent_class = g_type_class_peek_parent (klass);
}


static void panda_client_instance_init (PandaClient * self) {
}


GType panda_client_get_type (void) {
	static volatile gsize panda_client_type_id__volatile = 0;
	if (g_once_init_enter (&panda_client_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PandaClientClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) panda_client_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PandaClient), 0, (GInstanceInitFunc) panda_client_instance_init, NULL };
		GType panda_client_type_id;
		panda_client_type_id = g_type_register_static (G_TYPE_OBJECT, "PandaClient", &g_define_type_info, 0);
		g_once_init_leave (&panda_client_type_id__volatile, panda_client_type_id);
	}
	return panda_client_type_id__volatile;
}




