/* PandaPlugin.c generated by valac 0.10.0, the Vala compiler
 * generated from PandaPlugin.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <libsoup/soup.h>


#define TYPE_PANDA_PLUGIN (panda_plugin_get_type ())
#define PANDA_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PANDA_PLUGIN, PandaPlugin))
#define IS_PANDA_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PANDA_PLUGIN))
#define PANDA_PLUGIN_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_PANDA_PLUGIN, PandaPluginIface))

typedef struct _PandaPlugin PandaPlugin;
typedef struct _PandaPluginIface PandaPluginIface;

struct _PandaPluginIface {
	GTypeInterface parent_iface;
	char* (*get_handler_path) (PandaPlugin* self);
	void (*request_handler) (PandaPlugin* self, SoupServer* server, SoupMessage* msg, const char* path, GHashTable* query, SoupClientContext* client);
};



GType panda_plugin_get_type (void) G_GNUC_CONST;
char* panda_plugin_get_handler_path (PandaPlugin* self);
void panda_plugin_request_handler (PandaPlugin* self, SoupServer* server, SoupMessage* msg, const char* path, GHashTable* query, SoupClientContext* client);



#line 3 "main.vala"
char* panda_plugin_get_handler_path (PandaPlugin* self) {
#line 3 "main.vala"
	return PANDA_PLUGIN_GET_INTERFACE (self)->get_handler_path (self);
#line 39 "PandaPlugin.c"
}


#line 3 "main.vala"
void panda_plugin_request_handler (PandaPlugin* self, SoupServer* server, SoupMessage* msg, const char* path, GHashTable* query, SoupClientContext* client) {
#line 3 "main.vala"
	PANDA_PLUGIN_GET_INTERFACE (self)->request_handler (self, server, msg, path, query, client);
#line 47 "PandaPlugin.c"
}


static void panda_plugin_base_init (PandaPluginIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType panda_plugin_get_type (void) {
	static volatile gsize panda_plugin_type_id__volatile = 0;
	if (g_once_init_enter (&panda_plugin_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (PandaPluginIface), (GBaseInitFunc) panda_plugin_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType panda_plugin_type_id;
		panda_plugin_type_id = g_type_register_static (G_TYPE_INTERFACE, "PandaPlugin", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (panda_plugin_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&panda_plugin_type_id__volatile, panda_plugin_type_id);
	}
	return panda_plugin_type_id__volatile;
}




