#!/usr/bin/env python

def build(bld):
	prog = bld(features='cc cprogram')
	# symbolic name used to reference this object
	prog.name = 'pandacommand'
	# name of the resulting program
	prog.target = 'pandacommand'
	prog.source = 'main.vala PandaClient.vala  PandaConfig.vala PandaPluginManager.vala PandaPluginLoader.vala PandaServer.vala PandaPlugin.vala '
	# libraries to link against
	prog.uselib = 'GTK+'
	# Vala packages to use
	prog.packages = 'gtk+-2.0 libsoup-2.4 gstreamer-0.10 gee-1.0 json-glib-1.0'
	# Extra vapi dirs
	#prog.vapi_dirs = '../my_lib'
	# Enable threading
	#prog.threading = True
